/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Categories {
  icon: string;
  id: Generated<string>;
  name: string;
  slug: string;
}

export interface Events {
  authors: Json;
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<string>;
  img: string | null;
  tag: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Groups {
  category_id: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  location: string | null;
  name: string;
  organizer_id: string | null;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  categories: Categories;
  events: Events;
  groups: Groups;
}
