/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Categories {
  icon: string;
  id: Generated<string>;
  name: string;
  slug: string;
}

export interface EventAttendants {
  created_at: Generated<Timestamp>;
  event_id: string;
  status: Generated<string>;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface Events {
  authors: Json;
  created_at: Generated<Timestamp>;
  description: string;
  group_id: string;
  id: Generated<string>;
  img: string | null;
  meeting_location: string;
  starts_at: Timestamp;
  status: string;
  tag: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface GroupMembers {
  group_id: string;
  joined_at: Generated<Timestamp>;
  role: Generated<string>;
  user_id: string;
}

export interface Groups {
  category_id: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  location: string | null;
  name: string;
  organizer_email: string | null;
  organizer_id: string | null;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface Notifications {
  created_at: Generated<Timestamp>;
  group_id: string;
  id: Generated<string>;
  message: string;
  priority: string;
  status: Generated<string>;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  password_hash: string;
}

export interface DB {
  categories: Categories;
  event_attendants: EventAttendants;
  events: Events;
  group_members: GroupMembers;
  groups: Groups;
  notifications: Notifications;
  sessions: Sessions;
  users: Users;
}
