import { appendFile } from "node:fs/promises";
import path from "node:path";
import { spawnSync } from "node:child_process";

function parseOption(argv, name) {
  const index = argv.indexOf(name);
  if (index === -1) return undefined;

  const value = argv[index + 1];
  if (!value || value.startsWith("--")) {
    throw new Error(`${name} requires a value`);
  }

  return value;
}

function formatTimestamp(date) {
  const pad = (value) => String(value).padStart(2, "0");

  return (
    [
      date.getUTCFullYear(),
      pad(date.getUTCMonth() + 1),
      pad(date.getUTCDate()),
    ].join("") +
    "-" +
    [
      pad(date.getUTCHours()),
      pad(date.getUTCMinutes()),
      pad(date.getUTCSeconds()),
    ].join("")
  );
}

function getShortSha({ repoRoot, env }) {
  if (env.GITHUB_SHA) {
    return env.GITHUB_SHA.slice(0, 7);
  }

  const result = spawnSync("git", ["rev-parse", "--short=7", "HEAD"], {
    cwd: repoRoot,
    encoding: "utf8",
  });

  if (result.status === 0) {
    return result.stdout.trim();
  }

  return "local";
}

export function getSourceDateEpoch({ repoRoot, env }) {
  if (env.SOURCE_DATE_EPOCH) {
    if (!/^\d+$/.test(env.SOURCE_DATE_EPOCH)) {
      throw new Error("SOURCE_DATE_EPOCH must be an integer Unix timestamp");
    }

    return env.SOURCE_DATE_EPOCH;
  }

  const result = spawnSync("git", ["show", "-s", "--format=%ct", "HEAD"], {
    cwd: repoRoot,
    encoding: "utf8",
  });

  if (result.status === 0 && /^\d+$/.test(result.stdout.trim())) {
    return result.stdout.trim();
  }

  return "0";
}

export function createArtifactDescriptor({
  appName,
  releasePrefix,
  repoRoot,
  artifactsRoot,
  argv,
  env,
}) {
  // Packaging metadata only. Runtime env is generated by BT-Infra from Secrets Manager.
  const timestamp = env.RELEASE_TIMESTAMP ?? formatTimestamp(new Date());
  const shortSha = getShortSha({ repoRoot, env });
  const artifactName =
    parseOption(argv, "--artifact-name") ??
    env.RELEASE_ARTIFACT_NAME ??
    `${appName}-${timestamp}-${shortSha}.tgz`;

  if (!artifactName.endsWith(".tgz")) {
    throw new Error("Release artifact name must end with .tgz");
  }

  return {
    appName,
    artifactName,
    artifactKey: `${releasePrefix}/${artifactName}`,
    artifactPath: path.join(artifactsRoot, artifactName),
    commitSha: env.GITHUB_SHA ?? shortSha,
  };
}

export async function writeGitHubOutputs(metadata, env) {
  if (!env.GITHUB_OUTPUT) return;

  await appendFile(
    env.GITHUB_OUTPUT,
    [
      `artifact_name=${metadata.artifactName}`,
      `artifact_key=${metadata.artifactKey}`,
      `artifact_path=${metadata.artifactPath}`,
      "",
    ].join("\n"),
  );
}
